#!/usr/bin/env python3
"""Validate that every CONFIG_* symbol cited in .claude/skills/ exists in deps/.

The Zephyr skill references are large hand/LLM-authored documents. The failure
mode that matters is a Kconfig symbol that was renamed or removed upstream:
`prj.conf` silently ignores unknown symbols, so a stale skill produces a build
that "works" but doesn't have the feature enabled.

This scans skill markdown for CONFIG_* tokens and checks each against the
symbol universe defined by the Kconfig files under deps/. It also compares the
`Validated against:` stamp in each SKILL.md with the current Zephyr checkout so
you can see when the references are due for a re-verification pass.

    mise run check-skills          # report + non-zero exit on unknown symbols
    mise run check-skills --list   # also print every resolved symbol

ponytail: this is a text scan, not a Kconfig parse -- it does not evaluate
`depends on`, `source` globs, or `$(module)` template substitution. Symbols
generated by Kconfig templates (per-module LOG_LEVEL choices) are pattern
exempted below; everything else that is legitimately absent goes in the
allowlist. Upgrade path if this gets noisy: drive it from a real kconfiglib
parse of a built app's Kconfig tree.
"""

from __future__ import annotations

import argparse
import fnmatch
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS = REPO / ".claude" / "skills"
DEPS = REPO / "deps"
ZEPHYR = DEPS / "zephyr"
ALLOWLIST = SKILLS / ".symbol-allowlist.txt"

# Capture trailing underscores so a prefix wildcard (`CONFIG_UART_STM32_*`,
# `CONFIG_NET_*`) is recognisable as one and skipped below -- truncating it
# instead would leave a plausible-looking but bogus symbol like CONFIG_NET.
# `CONFIG_CONFIG_*` is always the "don't prefix your Kconfig with CONFIG_"
# anti-example, never a real symbol.
CONFIG_TOKEN = re.compile(r"\bCONFIG_(?!CONFIG_)([A-Z0-9_]+)")
CONFIG_DEF = re.compile(r"^\s*(?:menu)?config\s+([A-Za-z0-9_]+)\s*$", re.MULTILINE)
STAMP = re.compile(r"^Validated against:\s*Zephyr\s+(\S+)\s+\(([0-9a-f]{7,40})", re.MULTILINE)

# Symbols synthesised by Kconfig templates rather than a literal `config FOO`.
# Zephyr's logging templates emit `config $(module)_LOG_LEVEL...`, which no
# amount of text scanning will resolve to a concrete name.
GENERATED = (re.compile(r"_LOG_LEVEL(_(DBG|INF|WRN|ERR|OFF|NONE|DEFAULT|INHERIT))?$"),)


def load_allowlist() -> tuple[list[str], dict[str, str]]:
    """Return (glob patterns, {pattern: reason}) from the allowlist file."""
    patterns: list[str] = []
    reasons: dict[str, str] = {}
    if not ALLOWLIST.exists():
        return patterns, reasons
    for raw in ALLOWLIST.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        pattern, _, reason = line.partition("#")
        pattern = pattern.strip()
        if pattern:
            patterns.append(pattern)
            reasons[pattern] = reason.strip()
    return patterns, reasons


def kconfig_universe() -> set[str]:
    """Every symbol defined by a `config`/`menuconfig` line under deps/."""
    syms: set[str] = set()
    for path in DEPS.rglob("Kconfig*"):
        if not path.is_file():
            continue
        try:
            text = path.read_text(errors="ignore")
        except OSError:
            continue
        syms.update(CONFIG_DEF.findall(text))
    return syms


def cited_symbols() -> dict[str, list[str]]:
    """{symbol: [relative paths citing it]} across all skill markdown."""
    cites: dict[str, list[str]] = {}
    for path in sorted(SKILLS.rglob("*.md")):
        rel = str(path.relative_to(SKILLS))
        for sym in set(CONFIG_TOKEN.findall(path.read_text())):
            cites.setdefault(sym, []).append(rel)
    return cites


def zephyr_head() -> tuple[str, str]:
    """(version, short sha) of the current Zephyr checkout."""
    version = "unknown"
    vf = ZEPHYR / "VERSION"
    if vf.exists():
        fields = dict(
            (k.strip(), v.strip())
            for k, _, v in (line.partition("=") for line in vf.read_text().splitlines())
            if k.strip()
        )
        version = "{}.{}.{}".format(
            fields.get("VERSION_MAJOR", "?"),
            fields.get("VERSION_MINOR", "?"),
            fields.get("PATCHLEVEL", "?"),
        )
    try:
        sha = subprocess.run(
            ["git", "-C", str(ZEPHYR), "rev-parse", "--short=12", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except OSError, subprocess.CalledProcessError:
        sha = "unknown"
    return version, sha


def check_stamps(version: str, sha: str) -> list[str]:
    """Warn about SKILL.md files with a missing or outdated validation stamp.

    Only the zephyr-* skills track the tree; others (e.g. poethepoet) version
    themselves independently.
    """
    warnings = []
    for skill in sorted(SKILLS.glob("zephyr-*/SKILL.md")):
        name = skill.parent.name
        m = STAMP.search(skill.read_text())
        if not m:
            warnings.append(f"{name}: no 'Validated against:' stamp")
        elif not sha.startswith(m.group(2)) and not m.group(2).startswith(sha):
            warnings.append(f"{name}: stamped {m.group(1)} ({m.group(2)}), tree is {version} ({sha})")
    return warnings


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--list", action="store_true", help="print resolved symbols too")
    args = ap.parse_args()

    if not ZEPHYR.exists():
        print("deps/zephyr missing -- run: mise run west-update", file=sys.stderr)
        return 2

    universe = kconfig_universe()
    cites = cited_symbols()
    patterns, reasons = load_allowlist()
    version, sha = zephyr_head()

    print(f"Zephyr tree:  {version} ({sha})")
    print(f"Kconfig defs: {len(universe)} symbols under deps/")
    print(f"Skills cite:  {len(cites)} distinct CONFIG_* symbols")

    unknown: dict[str, list[str]] = {}
    allowed = 0
    for sym, files in sorted(cites.items()):
        if sym in universe:
            if args.list:
                print(f"  ok        CONFIG_{sym}")
            continue
        if sym.endswith("_"):
            continue  # prose prefix wildcard, e.g. `CONFIG_UART_STM32_*`
        if any(p.search(sym) for p in GENERATED):
            continue
        hit = next((p for p in patterns if fnmatch.fnmatchcase(sym, p)), None)
        if hit:
            allowed += 1
            continue
        unknown[sym] = files

    print(f"Allowlisted:  {allowed}")

    warnings = check_stamps(version, sha)
    if warnings:
        print("\nStale or missing validation stamps:")
        for w in warnings:
            print(f"  ! {w}")

    if unknown:
        print(f"\nUnknown symbols ({len(unknown)}) -- renamed, removed, or need allowlisting:")
        for sym, files in unknown.items():
            print(f"  CONFIG_{sym}")
            for f in sorted(files):
                print(f"      {f}")
        print(f"\nFix the skill, or add the symbol to {ALLOWLIST.relative_to(REPO)} with a reason.")
        return 1

    print("\nAll cited CONFIG_* symbols resolve against the current tree.")
    return 1 if warnings else 0


if __name__ == "__main__":
    sys.exit(main())
