# Drivers
CONFIG_LED_STRIP=y

# Enable when re-activating the neokey block in the overlay:
# CONFIG_MFD_ADAFRUIT_SEESAW=y
# CONFIG_GPIO_ADAFRUIT_SEESAW=y
# CONFIG_LED_STRIP=y
# CONFIG_LED_STRIP_ADAFRUIT_SEESAW=y